---
- name: Update system, install OSCAP, generate and run CIS Level 2 remediation script
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Create a non-root user with sudo privileges
      ansible.builtin.user:
        name: user1
        shell: /bin/bash
        groups: wheel
        # Replace the hash below with one you generate for P@ssw0rd@IBM
        password: "$6$ThiIK8enApAcAI6P$PVAjhaAF9OUPNZx6/8YopsKeWf5V4rpNOTLlNocre2xkDrfvxCHAac/VFoMmi4wiV9IXWa5sh70FEBS/99.ky/"
        state: present
        create_home: yes

    - name: Ensure .ssh directory exists for user1
      ansible.builtin.file:
        path: /home/user1/.ssh
        state: directory
        mode: '0700'
        owner: user1
        group: user1

    - name: Add SSH key to authorized_keys for user1
      ansible.builtin.authorized_key:
        user: user1
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeK6wARzHAI8YaRMPIg1ymkIl6TD0aq1gTYCswpc6vr2QN1XmoVtYxZGMiNypldl5ouzZW7h4fSqigbSOY7zJy7IqmGTcRLDhXTQYNAf4l3oXpqNhPetl3fEkqyh46LRS24+6No+7mwCWc1ilFwyZYS1MKVBLjg1a4HOxaYg8Fl1ysyhEOzLI40pT9K17LOEtRMD6uAjTwMzwQ6GolL07IfKejnv6Dd2u6mp/VbBIoCznBDFTrNBkPbIFFEbNbWe8evMMqY+cGOY+Zv6wwkTMEB4FXbdbmaBMgbtM6ONCwNeJyU+qin7WUAwI2mLttY8cXl1UgtHs+1d+cnYjzGch41tavPuWZu45v5jgWhUHYDABCdlbLf3ODGNbM2Tafvzx6zJQcUQ9obDkSpDpfnb/bPBMa2H/7LtGG2mn/IUW8N5ZCQ54Ge/PNOYpwjWBTJG4zb1Z2AnysSd3VmoAM8LCXohcNxE9EBpDN4AotXMiZIPqx1PwQNLX71Pr8FIqnxG5LTtpeZzAIy9bXOmBQn4xtOQSD3TVu0zj9Yf8Cz2ODkMFfHXwsFcS2kU9zTTiPIQY82aSVGRiWe3FvOaMYD8EzlKECm4w5pi0mY4Yp1NDJeK5BSR6aV9QlV0wLel48OQr93BJyViEbAZmKiVnQZxYgPi1fr3tFr4bzVd1l/AdR2w== jcalalang@ph.ibm.com"

    - name: Install OpenSCAP and SCAP Security Guide
      ansible.builtin.yum:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Generate CIS Level 2 remediation script
      ansible.builtin.command: >
        bash -c "oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_cis
        /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml > /tmp/remediate.sh"
      register: generate_fix_result
      changed_when: false

    - name: Make the remediation script executable
      ansible.builtin.file:
        path: /tmp/remediate.sh
        mode: '0755'
        state: file

    - name: Run the remediation script
      ansible.builtin.command: /tmp/remediate.sh
      register: remediate_script_result

    - name: Display remediation script output
      ansible.builtin.debug:
        msg: "{{ remediate_script_result.stdout }}"
