---
- name: Update system, install OSCAP, generate and run CIS Level 2 remediation script
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install OpenSCAP and SCAP Security Guide
      ansible.builtin.yum:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Generate CIS Level 2 remediation script
      ansible.builtin.command: >
        bash -c "oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_cis
        /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml > /tmp/remediate.sh"
      register: generate_fix_result
      changed_when: false

    - name: Make the remediation script executable
      ansible.builtin.file:
        path: /tmp/remediate.sh
        mode: '0755'
        state: file

    - name: Run the remediation script
      ansible.builtin.command: /tmp/remediate.sh
      register: remediate_script_result

    - name: Display remediation script output
      ansible.builtin.debug:
        msg: "{{ remediate_script_result.stdout }}"