---
- name: Force mount volumes to specified mount points
  hosts: all
  become: yes
  vars:
    volumes:
      - device: "/dev/vdb"
        mount_point: "/home"
        filesystem: "ext4"
        opts: "defaults,nodev"
      - device: "/dev/vdc"
        mount_point: "/var"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vdd"
        mount_point: "/var/log"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vde"
        mount_point: "/var/log/audit"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vdf"
        mount_point: "/var/tmp"
        filesystem: "ext4"
        opts: "defaults,nodev,nosuid,noexec"
      - device: "/dev/vdg"
        mount_point: "/dev/shm"
        filesystem: "tmpfs"
        opts: "defaults,nodev,nosuid,noexec"

  tasks:
    - name: Ensure the mount point directory exists
      file:
        path: "{{ item.mount_point }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      with_items: "{{ volumes }}"

    - name: Mount the volume (force overwrite existing mount point)
      mount:
        path: "{{ item.mount_point }}"
        src: "{{ item.device }}1"
        fstype: "{{ item.filesystem }}"
        opts: "{{ item.opts }}"
        state: mounted
      with_items: "{{ volumes }}"