---
- name: Partition, format, and mount disks starting from vdd
  hosts: all
  become: yes
  vars:
    volumes:
      - device: "/dev/vdb"
        mount_point: "/var"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vdc"
        mount_point: "/var/log"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vdd"
        mount_point: "/var/log/audit"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vde"
        mount_point: "/var/tmp"
        filesystem: "ext4"
        opts: "defaults,nodev,nosuid,noexec"
      - device: "/dev/vdf"
        mount_point: "/dev/shm"
        filesystem: "tmpfs"
        opts: "defaults,nodev,nosuid,noexec"

  tasks:
    - name: Check if devices are already partitioned
      command: "lsblk -n -o NAME {{ item.device | basename }}1"
      register: partition_check
      failed_when: false
      changed_when: false
      with_items: "{{ volumes }}"
      when: item.filesystem != "tmpfs"

    - name: Partition the volumes if not already partitioned
      shell: |
        echo -e 'o\nn\np\n1\n\n\nw' | fdisk {{ item.device }}
      args:
        executable: /bin/bash
      when: 
        - item.filesystem != "tmpfs"
        - "'1' not in (partition_check.results | selectattr('item', 'equalto', item) | map(attribute='stdout') | list | first | default(''))"
      with_items: "{{ volumes }}"

    - name: Format the volume if not already formatted
      filesystem:
        dev: "{{ item.device }}1"
        fstype: "{{ item.filesystem }}"
      when: item.filesystem != "tmpfs"
      with_items: "{{ volumes }}"

    - name: Create mount point directory
      file:
        path: "{{ item.mount_point }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      with_items: "{{ volumes }}"

    - name: Mount the volume
      mount:
        path: "{{ item.mount_point }}"
        src: "{{ item.device }}1"
        fstype: "{{ item.filesystem }}"
        opts: "{{ item.opts }}"
        state: mounted
      when: item.filesystem != "tmpfs"
      with_items: "{{ volumes }}"

    - name: Persist the mount in /etc/fstab
      blockinfile:
        path: /etc/fstab
        block: |
          {{ item.device }}1 {{ item.mount_point }} {{ item.filesystem }} {{ item.opts }} 0 2
      when: item.filesystem != "tmpfs"
      with_items: "{{ volumes }}"
