---
- name: Prepare and mount volumes
  hosts: all
  become: yes
  vars:
    volumes:
      - device: "/dev/vdb"
        mount_point: "/home"
        filesystem: "ext4"
        opts: "defaults,nodev"
      - device: "/dev/vdc"
        mount_point: "/var"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vdd"
        mount_point: "/tmp"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vde"
        mount_point: "/var/log"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vdf"
        mount_point: "/var/log/audit"
        filesystem: "ext4"
        opts: "defaults"
      - device: "/dev/vdg"
        mount_point: "/var/tmp"
        filesystem: "ext4"
        opts: "defaults,nodev,nosuid,noexec"
      - device: "/dev/vdh"
        mount_point: "/dev/shm"
        filesystem: "tmpfs"
        opts: "defaults,nodev,nosuid,noexec"

  tasks:
    - name: Ensure the mount point directory exists
      file:
        path: "{{ item.mount_point }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      with_items: "{{ volumes }}"

    - name: Create a partition if not already partitioned
      shell: |
        echo -e 'o\nn\np\n1\n\n\nw' | fdisk {{ item.device }}
      args:
        executable: /bin/bash
      when: item.filesystem != "tmpfs"
      with_items: "{{ volumes }}"
      register: partition_result
      failed_when: false

    - name: Format the partition if not already formatted
      filesystem:
        dev: "{{ item.device }}1"
        fstype: "{{ item.filesystem }}"
      when: item.filesystem != "tmpfs"
      with_items: "{{ volumes }}"
      register: format_result
      failed_when: false

    - name: Mount the volume (force overwrite existing mount point)
      mount:
        path: "{{ item.mount_point }}"
        src: "{{ item.device }}1"
        fstype: "{{ item.filesystem }}"
        opts: "{{ item.opts }}"
        state: mounted
      with_items: "{{ volumes }}"
